import Config

# Do not print debug messages in production
config :logger, level: System.get_env("ZARYN_LOGGER_LEVEL", "info") |> String.to_atom()

config :zaryn, :mut_dir, System.get_env("ZARYN_MUT_DIR", "data")

config :zaryn, Zaryn.Bootstrap,
  reward_address: System.get_env("ZARYN_REWARD_ADDRESS", "") |> Base.decode16!(case: :mixed)

config :zaryn, Zaryn.Bootstrap.Sync,
  # 15 days
  out_of_sync_date_threshold:
    System.get_env("ZARYN_BOOTSTRAP_OUT_OF_SYNC_THRESHOLD", "54000") |> String.to_integer()

# TODO: provide the true addresses for the genesis ZARYN distribution
# config :zaryn, ArchEthic.Bootstrap.NetworkInit, genesis_pools: []

config :zaryn, Zaryn.BeaconChain.SlotTimer,
  # Every 10 minutes
  interval: System.get_env("ZARYN_BEACON_CHAIN_SLOT_TIMER_INTERVAL", "0 */10 * * * * *")

config :zaryn, Zaryn.BeaconChain.SummaryTimer,
  # Every day at midnight
  interval: System.get_env("ZARYN_BEACON_CHAIN_SUMMARY_TIMER_INTERVAL", "0 0 0 * * * *")

config :zaryn, Zaryn.Crypto,
  root_ca_public_keys: [
    tpm: System.get_env("ZARYN_CRYPTO_ROOT_CA_TPM_PUBKEY", "") |> Base.decode16!(case: :mixed)
  ],
  key_certificates_dir: System.get_env("ZARYN_CRYPTO_CERT_DIR", "~/aebot/key_certificates")

config :zaryn,
       Zaryn.Crypto.NodeKeystore,
       (case(System.get_env("ZARYN_CRYPTO_NODE_KEYSTORE_IMPL", "TPM")) do
          "TPM" ->
            Zaryn.Crypto.NodeKeystore.TPMImpl

          "SOFTWARE" ->
            Zaryn.Crypto.NodeKeystore.SoftwareImpl
        end)

# TODO: to remove when the implementation will be detected
config :zaryn,
       Zaryn.Crypto.SharedSecretsKeystore,
       Zaryn.Crypto.SharedSecretsKeystore.SoftwareImpl

config :zaryn, Zaryn.DB.CassandraImpl, host: System.get_env("ZARYN_DB_HOST", "127.0.0.1:9042")

config :zaryn, Zaryn.Governance.Pools,
  # TODO: provide the true addresses of the members
  initial_members: [
    technical_council: [],
    ethical_council: [],
    foundation: [],
    uniris: []
  ]

config :zaryn,
       Zaryn.Networking.IPLookup,
       (case(System.get_env("ZARYN_NETWORKING_IMPL", "NAT")) do
          "NAT" ->
            Zaryn.Networking.IPLookup.NAT

          "STATIC" ->
            Zaryn.Networking.IPLookup.Static

          "IPFY" ->
            Zaryn.Networking.IPLookup.IPIFY
        end)

config :zaryn, Zaryn.Networking.IPLookup.Static, hostname: System.get_env("ZARYN_STATIC_IP")

config :zaryn, Zaryn.OracleChain.Scheduler,
  # Poll new changes every minute
  polling_interval: System.get_env("ZARYN_ORACLE_CHAIN_POLLING_INTERVAL", "0 * * * * *"),
  # Aggregate chain every day 10 minute before midnight
  summary_interval: System.get_env("ZARYN_ORACLE_CHAIN_SUMMARY_INTERVAL", "0 50 0 * * * *")

config :zaryn, Zaryn.Reward.NetworkPoolScheduler,
  # Every month
  interval: System.get_env("ZARYN_REWARD_SCHEDULER_INTERVAL", "0 0 0 1 * * *")

config :zaryn,
       Zaryn.Crypto.SharedSecretsKeystore,
       Zaryn.Crypto.SharedSecretsKeystore.SoftwareImpl

config :zaryn, Zaryn.SharedSecrets.NodeRenewalScheduler,
  # Every day at 23:50:00
  interval: System.get_env("ZARYN_SHARED_SECRETS_RENEWAL_SCHEDULER_INTERVAL", "0 50 0 * * * *"),
  # Every day at midnight
  application_interval:
    System.get_env("ZARYN_SHARED_SECRETS_APPLICATION_INTERVAL", "0 0 0 * * * *")

config :zaryn, Zaryn.SelfRepair.Scheduler,
  # Every day at 00:05:00
  # To give time for the beacon chain to produce summary
  interval: System.get_env("ZARYN_SELF_REPAIR_SCHEDULER_INTRERVAL", "0 5 0 * * * *")

config :zaryn, Zaryn.P2P.Endpoint,
  port: System.get_env("ZARYN_P2P_PORT", "3002") |> String.to_integer()

config :zaryn, Zaryn.P2P.BootstrappingSeeds,
  backup_file: System.get_env("ZARYN_P2P_BOOTSTRAPPING_SEEDS_FILE", "p2p/seeds"),
  # TODO: define the default list of P2P seeds once the network will be more open to new miners
  genesis_seeds: System.get_env("ZARYN_P2P_BOOTSTRAPPING_SEEDS")

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :zaryn, ZarynWeb.Endpoint,
  http: [:inet6, port: System.get_env("ZARYN_HTTP_PORT", "8080") |> String.to_integer()],
  url: [host: "*", port: System.get_env("ZARYN_HTTP_PORT", "8080") |> String.to_integer()],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  root: ".",
  version: Application.spec(:zaryn, :vsn),
  check_origin: false,
  https: [
    port: System.get_env("ZARYN_HTTPS_PORT", "4443") |> String.to_integer(),
    cipher_suite: :strong,
    keyfile: System.get_env("ZARYN_WEB_SSL_KEY_PATH", ""),
    certfile: System.get_env("ZARYN_WEB_SSL_CERT_PATH", ""),
    transport_options: [socket_opts: [:inet6]]
  ]

# force_ssl: [hsts: true]
